#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "searx"
name = "Searx"
description.en = "Privacy-respecting, hackable metasearch engine"
description.fr = "Méta-moteur de recherche respectueux de la vie privée et bidouillable"
description.de = "Meta-Suchmaschine, die den Privatsphäre wahrt und 'hackable' ist"

version = "1.1.0~ynh3"

maintainers = []

[upstream]
license = "AGPL-3.0-or-later"
website = "https://searx.github.io/searx/"
demo = "https://demo.yunohost.org/searx/"
admindoc = "https://github.com/searx/searx/wiki"
code = "https://github.com/searx/searx"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/searx"

    [install.init_main_permission]
    help.en = "If enabled, Searx will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Searx sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    help.de = "Wenn aktiviert, ist Searx für Personen zugänglich, die kein Konto haben. Dies kann später über den Webadmin geändert werden"
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/searx/searx/archive/refs/tags/v1.1.0.tar.gz"
    sha256 = "fc17371a02ee1d73896c2ac9c55b1ec90e5171fd2eea060b8867fc7efb63d725"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "git",
        "build-essential",
        "libxslt-dev",
        "python3-dev",
        "python3-venv",
        "python3-pip",
        "python3-cffi",
        "python3-babel,zlib1g-dev",
        "libffi-dev",
        "libssl-dev",
        "python3-lxml",
        "uwsgi",
        "uwsgi-plugin-python3",
        "shellcheck",
    ]
