#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=uwsgi --action=stop

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

path_no_root=${path%/}
# Create a dedicated NGINX config
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# RECONFIGURING SEARX
#=================================================
ynh_script_progression "Reconfiguring Searx..."

#ynh_replace --match="base_url : https://${old_domain}${old_path%/}/" --replace="base_url : https://${new_domain}${new_path%/}/" --file="$install_dir/searx/settings.yml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=uwsgi-app@$app.service --action=restart --wait_until="spawned uWSGI master process" --log_path="/var/log/uwsgi/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
